// app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import MobileNav from "@/components/MobileNav";
import { UserSessionProvider } from "@/context/SessionContext";
import { ReviewsProvider } from "@/context/ReviewsContext";
import { DashboardProvider } from "@/context/DashboardContext";
import { Toaster } from "react-hot-toast"; // Import the Toaster component

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "travel nemo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserSessionProvider>
          <DashboardProvider>
            <ReviewsProvider>
              <main>
                <Header />
                {children}
                <MobileNav />
              </main>{" "}
              <Toaster /> {/* Add the Toaster component here */}
            </ReviewsProvider>
          </DashboardProvider>
        </UserSessionProvider>
      </body>
    </html>
  );
}
